name: Build
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/init

      - name: Build project
        run: npm run build

      - name: Run checks
        run: npm run check
