name: Lint
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/init

      - name: Run linter
        run: npm run lint
